all: misat orisat

misat:	SAT-alumnes.cpp
	g++ -O3 -Wall SAT-alumnes.cpp -o misat

orisat:	SAT-alumnes-1aVersio.cpp
	g++ -O3 -Wall SAT-alumnes-1aVersio.cpp -o misat

orisat-rename:	SAT-alumnes-1aVersio.cpp
	g++ -O3 -Wall SAT-alumnes-1aVersio.cpp -o orisat
