# file = miSudoku
#file = miSudoku teams events newBusCompany

# $(file): $(file).pl
# 	swipl -q -O -g main --stand_alone=true -o $(file) -c $(file).pl

minColoring: minColoring.pl
	swipl -q -O -g main --stand_alone=true -o minColoring -c minColoring.pl

towers: towers.pl
	swipl -q -O -g main --stand_alone=true -o towers -c towers.pl

gangsters: gangsters.pl
	swipl -q -O -g main --stand_alone=true -o gangsters -c gangsters.pl
